# Generated by Django 2.2.3 on 2019-09-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_gas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterModelOptions(
            name='gas',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='gas',
            name='date',
            field=models.DateField(verbose_name='Car Fuel date'),
        ),
    ]
