# Generated by Django 2.2.3 on 2019-09-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20190911_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='features',
            field=models.ManyToManyField(to='main_app.Feature'),
        ),
    ]
